ShopLaptop/Controllers/MainController.cs
using ShopLaptop.Common;
using ShopLaptop.Models.DBContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopLaptop.Controllers
{
    public class MainController : Controller
    {
        // GET: Main
        ShopLaptionDbContextDataContext context = null;

        public void SetViewbag(long? selectedID = null)
        {
            var dao = new CategoryDao();
            ViewBag.Categorys = dao.brand();

        }
        public void SetRelatedProduct()
        {
            context = new ShopLaptionDbContextDataContext();
            var listRelatedPro = context.Products.ToList();
            ViewBag.RelatedProducts = listRelatedPro;

        }

        public ActionResult Index()
        {
            SetViewbag();
            context = new ShopLaptionDbContextDataContext();
            List<Product> products = context.Products.ToList();
            return View(products);
        }

        public ActionResult Details(long ID)
        {
            SetViewbag();
            SetRelatedProduct();
            context = new ShopLaptionDbContextDataContext();
            var product = context.Products.SingleOrDefault(x => x.ID == ID);
            return View(product);
        }

        public ActionResult FullProduct()
        {
            SetViewbag();
            context = new ShopLaptionDbContextDataContext();
            List<Product> products = context.Products.ToList();
            return View(products);
        }

        public ActionResult ShowByBrand(string brand)
        {
            SetViewbag();
            SetRelatedProduct();
            context = new ShopLaptionDbContextDataContext();
            var brandThisProduct = context.Products.Where(x => x.Brand == brand).ToList();
            return View(brandThisProduct);
        }
    }
}

ShopLaptop/Views/Main/Details.cshtml
@model ShopLaptop.Models.DBContext.Product
@using ShopLaptop.Models.DBContext;
@using ShopLaptop.Models;

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-9 col-md-12">
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="product_tab sidebar fix">

                <div class="tab-content produc_tab_c">
                    <div class="tab-pane fade show active" id="p_tab1" role="tabpanel">
                        <div class="modal_img">
                            <a href="#"><img src="@Url.Content(Model.Image)" alt=""></a>
                            <div class="img_icone">
                                <img src="@Url.Content(Model.Image)" alt="">
                            </div>
                            <div class="view_img">
                                <a class="large_view" href="@Url.Content(Model.Image)"><i class="fa fa-search-plus"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="product_d_right">
                <h1>@Model.Name</h1>
                <div class="content_price mb-15">
                    <span>Màn hình - </span>
                    <span style="font-size: 18px; font-weight: normal !important;">@Model.Screen</span>
                </div>
                <div class="content_price mb-15">
                    <span>CPU - </span>
                    <span style="font-size: 18px; font-weight: normal !important;" class="">@Model.CPU</span>
                </div>
                <div class="content_price mb-15">
                    <span>RAM - </span>
                    <span style="font-size: 18px; font-weight: normal !important;" class="">@Model.RAM</span>
                </div>
                <div class="content_price mb-15">
                    <span>Card đồ họa - </span>
                    <span style="font-size: 18px; font-weight: normal !important;" class="">@Model.Card</span>
                </div>
                <div class="content_price mb-15">
                    <span>Ổ cứng - </span>
                    <span style="font-size: 18px; font-weight: normal !important;" class="">@Model.Disk</span>
                </div>
                <div class="content_price mb-15">
                    <span>Tình trạng - </span>
                    @if (Model.Quantity == 0)
                    {
                        <span style="font-size: 18px; font-weight: normal !important;" class="">Hết hàng</span>
                    }
                    else
                    {
                        <span style="font-size: 18px; font-weight: normal !important;" class="">Còn hàng</span>
                    }
                </div>
                <div class="box_quantity mb-20">
                    @if (Model.Quantity == 0)
                    {
                        <a style="background: red;" href="#"><i class="fa fa-shopping-cart"></i>Hết hàng</a>
                    }
                    else
                    {
                        <a href="@Url.Action("ThemGioHang", "Card", new { @ID = Model.ID, @url = Request.Url.ToString()})" type="submit"><i class="fa fa-shopping-cart"></i>Thêm vào giỏ</a>
                    }

                </div>

                <div class="product_stock mb-20">
                    <p></p>
                    <span>Hàng chính hảng</span>
                </div>
                <div class="wishlist-share">
                    <h4>Chia sẻ:</h4>
                    <ul>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                        <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
                        <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>

            </div>
        </div>
    </div>
    <!--Related Products area start-->
    <div class="new_product_area">
        <div class="block_title">
            <h3>Sản phẩm tương tự</h3>
        </div>
        <div class="row">
            <div class="product_active owl-carousel">
                @foreach (var item in ViewBag.RelatedProducts)
                {
                    if (item.Brand == Model.Brand)
                    {
                        <div class="col-lg-3">
                            <div class="single_product">
                                <div class="product_thumb">
                                    <a href="#"><img src="@Url.Content(item.Image)" alt=""></a>
                                    <div class="img_icone" style="width: 252px !important; height: 250px !important;">
                                        <img style="background-size:cover; width: 252px !important; height: 100%!important;" src="@Url.Content(item.Image)" alt="">
                                    </div>
                                    <div class="product_action">
                                        @if (item.Quantity == 0)
                                        {
                                            <a style="background: red;" href="#"><i class="fa fa-shopping-cart"></i>Hết hàng</a>
                                        }
                                        else
                                        {
                                            <a href="@Url.Action("ThemGioHang", "Card", new { @masp = Model.Code, @url = Request.Url.ToString()})"> <i class="fa fa-shopping-cart"></i>Thêm vào giỏ</a>
                                        }

                                    </div>
                                </div>
                                <div class="product_content">
                                    <span class="product_price">@item.Price</span>
                                    <h3 class="product_title"><a href="single-product.html">@item.Name</a></h3>
                                </div>
                                <div class="product_info">
                                    <ul>
                                        <li><a href="@Url.Action("Details", new { ID = item.ID})">Chi tiết</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
    <!--Related Products area end-->

</div>

ShopLaptop/Views/Main/FullProduct.cshtml
@model IEnumerable<ShopLaptop.Models.DBContext.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-9 col-md-12">
    <!--banner slider start-->
    <div class="banner_slider mb-35">
        <img src="~/Assets/Image/Banner/banner_big_1.jpg" alt="">
    </div>
    <!--banner slider start-->
    <!--shop toolbar start-->
    <div class="shop_toolbar list_toolbar mb-35">
        <div class="list_button">
            <ul class="nav" role="tablist">
                <li>
                    <a class="active" data-toggle="tab" href="#list" role="tab" aria-controls="list" aria-selected="true"><i class="fa fa-th-list"></i></a>
                </li>
                <li>
                    <a data-toggle="tab" href="#large" role="tab" aria-controls="large" aria-selected="false"><i class="fa fa-th-large"></i></a>
                </li>
            </ul>
        </div>
    </div>
    <!--shop toolbar end-->
    <!--shop tab product-->
    <div class="shop_tab_product">
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade " id="large" role="tabpanel">
                <div class="row">
                    @foreach (var laptop in Model)
                    {
                        <div class="col-lg-4 col-md-6">
                            <div class="single_product">
                                <div class="product_thumb">
                                    <a href="single-product.html"><img src="@Url.Content(laptop.Image)" alt=""></a>
                                    <div class="hot_img">
                                        <img src="@Url.Content(laptop.Image)" alt="">
                                    </div>
                                    <div class="product_action">
                                        @if (laptop.Quantity == 0)
                                        {
                                            <a style="background: red;" href="#"><i class="fa fa-shopping-cart"></i>Hết hàng</a>
                                        }
                                        else
                                        {
                                            <a href="@Url.Action("ThemGioHang", "Card", new { @ID = laptop.ID, @url = Request.Url.ToString()})" type="submit"><i class="fa fa-shopping-cart"></i>Thêm vào giỏ</a>
                                        }
                                    </div>
                                </div>
                                <div class="product_content">
                                    <span class="product_price">@laptop.Price</span>
                                    <h3 class="product_title"><a href="single-product.html">@laptop.Name</a></h3>
                                </div>
                                <div class="product_info">
                                    <ul>
                                        <li><a href="@Url.Action("Details", "Main", new { ID = laptop.ID})">Chi tiết</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="tab-pane fade show active" id="list" role="tabpanel">
                @foreach (var laptop in Model)
                {
                    <div class="product_list_item mb-35">
                        <div class="row align-items-center">
                            <div class="col-lg-4 col-md-6 col-sm-6">
                                <div class="product_thumb">
                                    <a href="single-product.html"><img src="@Url.Content(laptop.Image)" alt=""></a>
                                    <div class="hot_img">
                                        <img src="@Url.Content(laptop.Image)" alt="">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-8 col-md-6 col-sm-6">
                                <div class="list_product_content">
                                    <div class="product_ratting">
                                        <ul>
                                            <li><a href="#"><i class="fa fa-star"></i></a></li>
                                            <li><a href="#"><i class="fa fa-star"></i></a></li>
                                            <li><a href="#"><i class="fa fa-star"></i></a></li>
                                            <li><a href="#"><i class="fa fa-star"></i></a></li>
                                            <li><a href="#"><i class="fa fa-star"></i></a></li>
                                        </ul>
                                    </div>
                                    <div class="list_title">
                                        <h3><a href="single-product.html">@laptop.Name</a></h3>
                                    </div>
                                    <p class="design">
                                        @laptop.Description
                                        <div class="content_price">
                                            <span>Giá</span>
                                            <span style="font-size: 18px; font-weight: normal !important;">@laptop.Price</span>
                                        </div>
                                        <div class="add_links">
                                            <ul>
                                                <li><a href="@Url.Action("ThemGioHang", "Card", new { @ID = laptop.ID, @url = Request.Url.ToString()})" title="add to cart"><i class="fa fa-shopping-cart" aria-hidden="true"></i></a></li>
                                                <li><a href="@Url.Action("Details", "Main", new { ID = laptop.ID})"><i class="fa fa-eye" aria-hidden="true"></i></a></li>
                                            </ul>
                                        </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>

        </div>
    </div>
    <!--shop tab product end-->
</div>

ShopLaptop/Views/Main/Index.cshtml
@model IEnumerable<ShopLaptop.Models.DBContext.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-9 col-md-12">
    <!--banner slider start-->
    <div class="banner_slider slider_1">
        <div class="slider_active owl-carousel">
            <div class="single_slider" style="background-image: url(../../Assets/Image/Banner/banner_big_1.jpg)">
                <div class="slider_content">
                    <div class="slider_content_inner">
                        <h1 style="font-family:monospace;">Thứ bạn tìm - Chúng tôi có</h1>
                        <p></p>
                    </div>
                </div>
            </div>
            <div class="single_slider" style="background-image: url(../../Assets/Image/Banner/banner_big_2.jpg)">
                <div class="slider_content">
                    <div class="slider_content_inner">
                        <h1 style="font-family:monospace;">Chinh phục mọi giới hạn</h1>
                    </div>
                </div>
            </div>
            <div class="single_slider" style="background-image: url(../../Assets/Image/Banner/banner_big_3.jpg)">
                <div class="slider_content">
                    <div class="slider_content_inner">
                        <h1 style="font-family:monospace;">Sự hài lòng của bạn là điều mong muốn của chúng tôi</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--banner slider start-->
    <!--new product area start-->
    <div class="new_product_area">
        <div class="block_title">
            <h3>LAPTOP</h3>
        </div>
        <div class="row">
            <div class="product_active owl-carousel">
                @foreach (var laptop in Model)
                {
                    if (laptop.Price < 22000000)
                    {
                        <div class="col-lg-3">
                            <div class="single_product">
                                <div class="product_thumb">
                                    <a href="#"><img src="@Url.Content(@laptop.Image)" alt=""></a>
                                    <div class="img_icone" style="width: 252px !important; height: 250px !important;">
                                        <img style="background-size:cover; width: 252px !important; height: 100%!important;" src="@Url.Content(@laptop.Image)" alt="">
                                    </div>
                                    <div class="product_action">
                                        @if (laptop.Quantity == 0)
                                        {
                                            <a style="background: red;" href="#"><i class="fa fa-shopping-cart"></i>Hết hàng</a>
                                        }
                                        else
                                        {
                                            <a href="@Url.Action("ThemGioHang", "Card", new { @ID = laptop.ID, @url = Request.Url.ToString()})" type="submit"><i class="fa fa-shopping-cart"></i>Thêm vào giỏ</a>
                                        }
                                    </div>
                                </div>
                                <div class="product_content">
                                    <span class="product_price">@laptop.Price</span>
                                    <h3 class="product_title"><a href="single-product.html">@laptop.Name</a></h3>
                                </div>
                                <div class="product_info">
                                    <ul>
                                        <li><a href="@Url.Action("Details", new { ID = laptop.ID})">Chi tiết</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
    <!--new product area start-->
    <!--featured product start-->
    <div class="featured_product">
        <div class="block_title">
            <h3>LAPTOP</h3>
        </div>
        <div class="row">
            <div class="product_active owl-carousel">
                @foreach (var laptop in Model)
                {
                    if (laptop.Price >= 22000000)
                    {
                        <div class="col-lg-3">
                            <div class="single_product">
                                <div class="product_thumb">
                                    <a href="#"><img src="@Url.Content(@laptop.Image)" alt=""></a>
                                    <div class="img_icone" style="width: 252px !important; height: 250px !important;">
                                        <img style="background-size:cover; width: 252px !important; height: 252px !important;" src="@Url.Content(@laptop.Image)" alt="">
                                    </div>
                                    <div class="product_action">
                                        @if (laptop.Quantity == 0)
                                        {
                                            <a style="background: red;" href="#"><i class="fa fa-shopping-cart"></i>Hết hàng</a>
                                        }
                                        else
                                        {
                                            <a href="@Url.Action("ThemGioHang", "Card", new { @ID = laptop.ID, @url = Request.Url.ToString()})" type="submit"><i class="fa fa-shopping-cart"></i>Thêm vào giỏ</a>
                                        }
                                    </div>
                                </div>
                                <div class="product_content">
                                    <span class="product_price">@laptop.Price</span>
                                    <h3 class="product_title"><a href="single-product.html">@laptop.Name</a></h3>
                                </div>
                                <div class="product_info">
                                    <ul>
                                        <li><a href="@Url.Action("Details", new { ID = laptop.ID})">Chi tiết</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
    <!--featured product end-->
</div>

ShopLaptop/Views/Main/ShowByBrand.cshtml
@model IEnumerable<ShopLaptop.Models.DBContext.Product>
@{
    ViewBag.Title = "ShowByBrand";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-9 col-md-12">
    <!--banner slider start-->
    <div class="banner_slider mb-35">
        <img src="~/Assets/Image/Banner/banner_big_3.jpg" alt="">
    </div>
    <!--banner slider start-->
    <!--shop toolbar start-->
    <div class="shop_toolbar list_toolbar mb-35">
        <div class="list_button">
            <ul class="nav" role="tablist">
                <li>
                    <a class="active" data-toggle="tab" href="#list" role="tab" aria-controls="list" aria-selected="true"><i class="fa fa-th-list"></i></a>
                </li>
                <li>
                    <a data-toggle="tab" href="#large" role="tab" aria-controls="large" aria-selected="false"><i class="fa fa-th-large"></i></a>
                </li>
            </ul>
        </div>
    </div>
    <!--shop toolbar end-->
    <!--shop tab product-->
    <div class="shop_tab_product">
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade " id="large" role="tabpanel">
                <div class="row">
                    @foreach (var laptop in Model)
                    {
                        <div class="col-lg-4 col-md-6">
                            <div class="single_product">
                                <div class="product_thumb">
                                    <a href="single-product.html"><img src="@Url.Content(laptop.Image)" alt=""></a>
                                    <div class="hot_img">
                                        <img src="@Url.Content(laptop.Image)" alt="">
                                    </div>
                                    <div class="product_action">
                                        @if (laptop.Quantity == 0)
                                        {
                                            <a style="background: red;" href="#"><i class="fa fa-shopping-cart"></i>Hết hàng</a>
                                        }
                                        else
                                        {
                                            <a href="@Url.Action("ThemGioHang", "Card", new { @ID = laptop.ID, @url = Request.Url.ToString()})" type="submit"><i class="fa fa-shopping-cart"></i>Thêm vào giỏ</a>
                                        }
                                    </div>
                                </div>
                                <div class="product_content">
                                    <span class="product_price">@laptop.Price</span>
                                    <h3 class="product_title"><a href="single-product.html">@laptop.Name</a></h3>
                                </div>
                                <div class="product_info">
                                    <ul>
                                        <li><a href="@Url.Action("Details", "Main", new { ID = laptop.ID})">Chi tiết</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="tab-pane fade show active" id="list" role="tabpanel">
                @foreach (var laptop in Model)
                {
                    <div class="product_list_item mb-35">
                        <div class="row align-items-center">
                            <div class="col-lg-4 col-md-6 col-sm-6">
                                <div class="product_thumb">
                                    <a href="single-product.html"><img src="@Url.Content(laptop.Image)" alt=""></a>
                                    <div class="hot_img">
                                        <img src="@Url.Content(laptop.Image)" alt="">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-8 col-md-6 col-sm-6">
                                <div class="list_product_content">
                                    <div class="product_ratting">
                                        <ul>
                                            <li><a href="#"><i class="fa fa-star"></i></a></li>
                                            <li><a href="#"><i class="fa fa-star"></i></a></li>
                                            <li><a href="#"><i class="fa fa-star"></i></a></li>
                                            <li><a href="#"><i class="fa fa-star"></i></a></li>
                                            <li><a href="#"><i class="fa fa-star"></i></a></li>
                                        </ul>
                                    </div>
                                    <div class="list_title">
                                        <h3><a href="single-product.html">@laptop.Name</a></h3>
                                    </div>
                                    <p class="design">
                                        @laptop.Description
                                        <div class="content_price">
                                            <span>Giá</span>
                                            <span style="font-size: 18px; font-weight: normal !important;">@laptop.Price</span>
                                        </div>
                                        <div class="add_links">
                                            <ul>
                                                <li>
                                                    @if (laptop.Quantity == 0)
                                                    {
                                                        <a style="background: red;" href="#"><i class="fa fa-shopping-cart"></i></a>
                                                    }
                                                    else
                                                    {
                                                        <a href="@Url.Action("ThemGioHang", "Card", new { @ID = laptop.ID, @url = Request.Url.ToString()})" type="submit"><i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
                                                    }
                                                </li>
                                                <li><a href="@Url.Action("Details", "Main", new { ID = laptop.ID})"><i class="fa fa-eye" aria-hidden="true"></i></a></li>
                                            </ul>
                                        </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>

        </div>
    </div>
    <!--shop tab product end-->
</div>