ShopLaptop/Areas/Admin/Controllers/BrandController.cs
using ShopLaptop.Common;
using ShopLaptop.Models.DBContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopLaptop.Areas.Admin.Controllers
{
    public class BrandController : BaseController
    {
        ShopLaptionDbContextDataContext context = null;

        public ActionResult Index()
        {
            context = new ShopLaptionDbContextDataContext();
            List<Category> categories = context.Categories.ToList();
            return View(categories);

        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Create(Category category)
        {
            context = new ShopLaptionDbContextDataContext();
            if (ModelState.IsValid)
            {
                var check_name = context.Categories.Any(a => a.Name.Equals(category.Name));
                if (check_name)
                {
                    ModelState.AddModelError("", "Thương hiệu này đã tồn tại !");
                    return View();
                }
                else
                {

                    category.CreatedBy = Session[CommonConstants.NAME_SESSION].ToString();
                    category.CreatedDate = DateTime.Now;
                    category.Name.ToUpper();

                    context.Categories.InsertOnSubmit(category);
                    context.SubmitChanges();

                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(long ID)
        {
            try
            {
                context = new ShopLaptionDbContextDataContext();
                var category = context.Categories.FirstOrDefault(x => x.ID == ID);
                context.Categories.DeleteOnSubmit(category);
                context.SubmitChanges();

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }

        }
    }
}

ShopLaptop/Areas/Admin/Controllers/HoaDonController.cs
using ShopLaptop.Models.DBContext;
using ShopLaptop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopLaptop.Areas.Admin.Controllers
{
    public class HoaDonController : BaseController
    {
        // GET: Admin/HoaDon

        ShopLaptionDbContextDataContext context = null;

        public ActionResult Index()
        {
            context = new ShopLaptionDbContextDataContext();
            var hd = context.Orders.Where(x => x.TinhTrang == false).ToList();
            return View(hd);
        }

        public ActionResult HoaDonDaXuLy()
        {
            context = new ShopLaptionDbContextDataContext();
            var hd = context.Orders.Where(x => x.TinhTrang == true).ToList();
            return View(hd);
        }

        public ActionResult XacNhanDonHang(string MaHD)
        {
            context = new ShopLaptionDbContextDataContext();

            var dh = context.Orders.SingleOrDefault(x => x.MaDH.Equals(MaHD));
            dh.TinhTrang = true;

            context.SubmitChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(string MaHD)
        {
            context = new ShopLaptionDbContextDataContext();
            var hd = context.Orders.SingleOrDefault(x => x.MaDH.Equals(MaHD));
            return View(hd);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Order order)
        {
            context = new ShopLaptionDbContextDataContext();
            try
            {
                if (ModelState.IsValid)
                {
                    var hd = context.Orders.SingleOrDefault(x => x.MaDH.Equals(order.MaDH));

                    hd.DiaChi = order.DiaChi;
                    hd.GhiChu = order.GhiChu;

                    context.SubmitChanges();
                }
                return RedirectToAction("Index");
            }
            catch(Exception)
            {
                ModelState.AddModelError("", "Chỉnh sửa thất bại !");
                return View();
            }
        }

        public ActionResult Details(string MaHD)
        {
            context = new ShopLaptionDbContextDataContext();
            List<OrderDetail> ctHD = context.OrderDetails.Where(x => x.MaDH.Equals(MaHD)).ToList();

            var temp = context.OrderDetails.FirstOrDefault(x => x.MaDH.Equals(MaHD));
            var dh = context.Orders.SingleOrDefault(x => x.MaDH == MaHD);


            ViewBag.CTDonhang = dh;

            ViewBag.TongTien = temp.Tong; // Tổng này là tổng của 1 món hàng hóa thôi mà.
            ViewBag.MaHoaDon = temp.MaDH;


            return View(ctHD);
        }

        [HttpPost]
        public ActionResult Delete(string MaHD)
        {
            try
            {
                context = new ShopLaptionDbContextDataContext();

                var hd = context.Orders.FirstOrDefault(x => x.MaDH == MaHD);
                var cthd = context.OrderDetails.FirstOrDefault(x => x.MaDH == MaHD);

                context.Orders.DeleteOnSubmit(hd);
                context.SubmitChanges();

                context.OrderDetails.DeleteOnSubmit(cthd);
                context.SubmitChanges();

                return RedirectToAction("Index");
            }

            catch (Exception)
            {
                return RedirectToAction("Index");
            }

        }
    }
}

ShopLaptop/Areas/Admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopLaptop.Areas.Admin.Common;
using ShopLaptop.Areas.Admin.Models;
using ShopLaptop.Models;
using ShopLaptop.Common;
using ShopLaptop.Models.DBContext;

namespace ShopLaptop.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        // GET: Admin/Login


        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public  ActionResult Index(LoginModel model)
        {
            using (ShopLaptionDbContextDataContext context = new ShopLaptionDbContextDataContext())
            {
                int check = 0;
                if (ModelState.IsValid)
                {
                    var res = context.Users.SingleOrDefault(x => x.UserName.Equals(model.UserName));
                    if (res == null) check = 0;
                    else
                    {
                        if (res.Password == model.Password) check = 1;
                        else check = - 1;
                    }
                    switch (check)
                    {
                        case 0:
                            {
                                ModelState.AddModelError("", "Tài khoản không tồn tại !");
                                break;
                            }
                        case 1:
                            {
                                var user = context.Users.SingleOrDefault(x => x.UserName == model.UserName);
                                var userSession = new UserLogin
                                {
                                    UserName = user.UserName,
                                    Name = user.Name,
                                    UserID = user.ID,
                                    Permission = (int)user.Permission
                                };

                                Session.Add(CommonConstants.USER_SESSION, userSession);
                                Session.Add(CommonConstants.NAME_SESSION, userSession.Name);
                                Session.Add(CommonConstants.IDUSER_SESSION, userSession.UserID);
                                Session.Add(CommonConstants.PERMISSION_SESSION, userSession.Permission);

                                return RedirectToActionPermanent("Index", "Home");
                            }
                        case -1:
                            {
                                ModelState.AddModelError("", "Mật khẩu không đúng !");
                                break;
                            }
                    }
                }
                return View("Index");
            } 
        }

        public ActionResult Logout()
        {
            Session.RemoveAll();
            return RedirectToAction("Index");
        }
    }
}

ShopLaptop/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopLaptop.Models.DBContext;
using ShopLaptop.Models;
using ShopLaptop.Common;
using ShopLaptop.Areas.Admin.Models;
using ShopLaptop.Code;

namespace ShopLaptop.Areas.Admin.Controllers
{
    public class UserController : BaseController
    {
        // GET: Admin/User

        ShopLaptionDbContextDataContext context = null;

        public ActionResult Index()
        {
            context = new ShopLaptionDbContextDataContext();
            List<User> users = context.Users.ToList();
            return View(users);

        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        public ActionResult Create(User user) 
        {
            context = new ShopLaptionDbContextDataContext();
            if (ModelState.IsValid)
            {
                var check_user = context.Users.Any(a => a.UserName.Equals(user.UserName));
                var check_email = context.Users.Any(a => a.Email.Equals(user.Email));
                var res_val = new MyValidate();

                if (check_user)
                {
                    ModelState.AddModelError("", "Tài khoản đã tồn tại !");
                    return View();
                }
                else if (check_email)
                {
                    ModelState.AddModelError("", "Email đã tồn tại !");
                    return View();
                }
                else if (res_val.isEmail(user.Email)==false)
                {
                    ModelState.AddModelError("", "Email không đúng định dạng !");
                    return View();
                }
                else if (res_val.IsValidPhone(user.Phone) == false)
                {
                    ModelState.AddModelError("", "Số điện thoại không đúng !");
                    return View();
                }
                else
                {

                    user.CreatedBy = Session[CommonConstants.NAME_SESSION].ToString();
                    user.CreatedDate = DateTime.Now;

                    context.Users.InsertOnSubmit(user);
                    context.SubmitChanges();

                    return RedirectToAction("Index");
                }
            }
            return  RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(long ID)
        {
            context = new ShopLaptionDbContextDataContext();
            var user = context.Users.SingleOrDefault(x => x.ID == ID);
            return View(user);
        }

        [HttpPost]
        public ActionResult Edit(User account)
        {
            context = new ShopLaptionDbContextDataContext();
            if (ModelState.IsValid)
            {


                var user = context.Users.SingleOrDefault(x => x.ID == account.ID);

                user.Name = account.Name;
                user.Address = account.Address;
                user.Email = account.Email;
                user.Phone = account.Phone;
                user.ModifiedDate = DateTime.Now;
                user.ModifiedBy = Session[CommonConstants.NAME_SESSION].ToString();
                context.SubmitChanges();

                return RedirectToAction("Index");
            }
            return View("Index");
        }

        public ActionResult Details(long ID)
        {
            context = new ShopLaptionDbContextDataContext();
            var user = context.Users.SingleOrDefault(x => x.ID == ID);
            return View(user);
        }

        [HttpPost]
        public ActionResult Delete(long ID)
        {
            try
            {
                context = new ShopLaptionDbContextDataContext();

                //if (Session[CommonConstants.PERMISSION_SESSION == 1])
                //{

                //}
                var user = context.Users.FirstOrDefault(x => x.ID == ID);
                context.Users.DeleteOnSubmit(user);
                context.SubmitChanges();

                return RedirectToAction("Index");
            }
            catch(Exception)
            {
                return RedirectToAction("Index");
            }
            
        }
    }
}

ShopLaptop/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="~/Assets/Admin/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <link href="~/Content/MyCustom.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="@Url.Action("Index","Home")">LAPTOP</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                @*<input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                    </div>*@
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="@Url.Action("Details","User", new { @ID = Convert.ToInt32(Session["IDUSER_SESSION"])})">Thông tin</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="@Url.Action("Logout", "Login")">Đăng xuất</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        @RenderPage("~/Areas/Admin/Views/Shared/_SideBar.cshtml")
        <div id="layoutSidenav_content">
            @RenderBody()

            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Shop bán laptop 2020</div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Assets/Admin/js/scripts.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="~/Assets/Admin/assets/demo/datatables-demo.js"></script>

</body>
</html>

ShopLaptop/Areas/Admin/Views/Shared/_Sidebar.cshtml
@{
    ViewBag.Title = "_SideBar";
}

<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Thanh quản lý</div>

                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBrand" aria-expanded="false" aria-controls="collapseBrand">
                    <div class="sb-nav-link-icon"><i class="fas fa-box"></i></div>
                    Thương hiệu
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseBrand" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="@Url.Action("Index", "Brand")">Các thương hiệu</a>
                        <a class="nav-link" href="@Url.Action("Create", "Brand")">Thêm thương hiệu</a>
                    </nav>
                </div>

                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseProduct" aria-expanded="false" aria-controls="collapseProduct">
                    <div class="sb-nav-link-icon"><i class="fas fa-laptop"></i></i></div>
                    Laptop
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseProduct" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="@Url.Action("Index", "Product")">Danh sách sản phẩm</a>
                        <a class="nav-link" href="@Url.Action("Create", "Product")">Thêm sản phẩm</a>
                    </nav>
                </div>
                @if (Convert.ToInt32(Session["PER_SESSION"]) == 1)
                {
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                        Quản lý người dùng
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="@Url.Action("Index", "User")">Danh sách người dùng</a>
                            <a class="nav-link" href="@Url.Action("Create", "User")">Thêm người dùng</a>
                        </nav>
                    </div>
                }

                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseOrder" aria-expanded="false" aria-controls="collapseOrder">
                    <div class="sb-nav-link-icon"><i class="fas fa-money-check-alt"></i></div>
                    Đơn hàng
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseOrder" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="@Url.Action("Index", "HoaDon")">Đơn đặt hàng</a>
                        <a class="nav-link" href="@Url.Action("HoaDonDaXuLy", "HoaDon")">Đã xử lý</a>
                    </nav>
                </div>
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Đang đăng nhập với:</div>
            @Session["NAME_SESSION"].ToString()
        </div>
    </nav>
</div>